version: '3.8'
services:

  #
  # janus-gateway
  #
  janus-gateway:
    image: 'serhiisatanenko/janus-gateway:0.2'
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
      - "7188:7188"
    volumes:
      - "./data/janus:/usr/local/etc/janus"
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    restart: always